apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservice-template
  title: Create a New Microservice
  description: Creates a production-ready microservice with CI/CD, monitoring, and documentation
  tags:
    - recommended
    - nodejs
    - python
    - go
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Service Name
          type: string
          description: Unique name for your service
          pattern: '^[a-z][a-z0-9-]*$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Brief description of the service
        owner:
          title: Owner Team
          type: string
          description: Team that owns this service
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Technical Specifications
      required:
        - language
        - database
      properties:
        language:
          title: Programming Language
          type: string
          enum:
            - nodejs
            - python
            - go
            - java
          enumNames:
            - Node.js (TypeScript)
            - Python (FastAPI)
            - Go (Gin)
            - Java (Spring Boot)
        database:
          title: Database Type
          type: string
          enum:
            - postgresql
            - mysql
            - mongodb
            - none
          default: postgresql
        cache:
          title: Cache Layer
          type: boolean
          default: true
          description: Add Redis caching layer
        messageQueue:
          title: Message Queue
          type: boolean
          default: false
          description: Add RabbitMQ/Kafka integration

    - title: Infrastructure Options
      properties:
        kubernetes:
          title: Deploy to Kubernetes
          type: boolean
          default: true
        namespace:
          title: Kubernetes Namespace
          type: string
          default: default
          ui:widget: hidden
          ui:options:
            dependencies:
              kubernetes: true
        replicas:
          title: Initial Replicas
          type: integer
          default: 2
          minimum: 1
          maximum: 10
        resources:
          title: Resource Size
          type: string
          enum:
            - small
            - medium
            - large
          enumNames:
            - Small (256Mi/100m)
            - Medium (512Mi/250m)
            - Large (1Gi/500m)
          default: medium

    - title: CI/CD & Observability
      properties:
        cicd:
          title: CI/CD Platform
          type: string
          enum:
            - github-actions
            - gitlab-ci
            - argocd
          default: github-actions
        monitoring:
          title: Enable Monitoring
          type: boolean
          default: true
        alerting:
          title: Enable PagerDuty Alerting
          type: boolean
          default: false

    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com

  steps:
    # Fetch base template
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton/${{ parameters.language }}
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          database: ${{ parameters.database }}
          cache: ${{ parameters.cache }}

    # Add Kubernetes manifests
    - id: fetch-k8s
      name: Add Kubernetes Manifests
      if: ${{ parameters.kubernetes }}
      action: fetch:template
      input:
        url: ./skeleton/kubernetes
        targetPath: ./k8s
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          replicas: ${{ parameters.replicas }}
          resources: ${{ parameters.resources }}

    # Add CI/CD pipeline
    - id: fetch-cicd
      name: Add CI/CD Pipeline
      action: fetch:template
      input:
        url: ./skeleton/cicd/${{ parameters.cicd }}
        targetPath: ./.github/workflows
        values:
          name: ${{ parameters.name }}
          language: ${{ parameters.language }}

    # Add monitoring configuration
    - id: fetch-monitoring
      name: Add Monitoring Configuration
      if: ${{ parameters.monitoring }}
      action: fetch:template
      input:
        url: ./skeleton/monitoring
        targetPath: ./monitoring
        values:
          name: ${{ parameters.name }}
          alerting: ${{ parameters.alerting }}

    # Generate catalog-info.yaml
    - id: catalog-info
      name: Generate Catalog Info
      action: catalog:write
      input:
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.name }}
            description: ${{ parameters.description }}
            annotations:
              github.com/project-slug: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
              backstage.io/techdocs-ref: dir:.
              argocd/app-name: ${{ parameters.name }}
          spec:
            type: service
            lifecycle: experimental
            owner: ${{ parameters.owner }}

    # Create GitHub repository
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        protectDefaultBranch: true
        requireCodeOwnerReviews: true

    # Register in catalog
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    # Create ArgoCD application
    - id: argocd
      name: Create ArgoCD Application
      if: ${{ parameters.cicd === 'argocd' }}
      action: argocd:create-application
      input:
        name: ${{ parameters.name }}
        namespace: ${{ parameters.namespace }}
        repoUrl: ${{ steps['publish'].output.remoteUrl }}
        path: k8s

    # Create PagerDuty service
    - id: pagerduty
      name: Create PagerDuty Service
      if: ${{ parameters.alerting }}
      action: pagerduty:create-service
      input:
        name: ${{ parameters.name }}
        description: ${{ parameters.description }}
        escalationPolicy: default

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: ArgoCD Application
        icon: argocd
        url: https://argocd.example.com/applications/${{ parameters.name }}
