apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rekor
  template:
    metadata:
      labels:
        app: rekor
    spec:
      containers:
      - name: rekor
        image: gcr.io/projectsigstore/rekor-server:latest
