apiVersion: v1
kind: Service
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: products-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
      - name: products-api
        image: fake-service/fake-service:latest
        env:
        - name: MESSAGE
          value: "Hello from Products API v1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-api-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limiting
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: products-api
            port:
              number: 80
