apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: hyness/spring-cloud-config-server:latest
        env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: https://github.com/spring-cloud-samples/config-repo
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
